{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"classify.ipynb","provenance":[]},"kernelspec":{"name":"python3","display_name":"Python 3"}},"cells":[{"cell_type":"code","metadata":{"id":"rqB1cD6obJoV","colab_type":"code","outputId":"0c2c5858-295a-4671-ad98-a0bee946ebf3","executionInfo":{"status":"ok","timestamp":1569898713575,"user_tz":-330,"elapsed":12467,"user":{"displayName":"Krunal Jain","photoUrl":"https://lh3.googleusercontent.com/a-/AAuE7mDTtvpOv4j7Rpc1DPsLIuoWRb73ePRFO18BzE2r9g=s64","userId":"06433844332726813114"}},"colab":{"base_uri":"https://localhost:8080/","height":34}},"source":["! git clone https://github.com/jainkrunal/HandGestureRecognition\n"],"execution_count":1,"outputs":[{"output_type":"stream","text":["fatal: destination path 'HandGestureRecognition' already exists and is not an empty directory.\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"H7dPwJVLbQeS","colab_type":"code","colab":{}},"source":["from skimage import transform\n","from skimage import data\n","import matplotlib.pyplot as plt\n","import os\n","import numpy as np\n","from skimage.color import rgb2gray\n","import random\n","import tensorflow as tf"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"VgOiEAq2bKsF","colab_type":"code","colab":{}},"source":["train_data = np.load(\"HandGestureRecognition/train_data.npy\") \n","test_data = np.load(\"HandGestureRecognition/test_data.npy\") \n"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"Nde7-sDTboIF","colab_type":"code","colab":{}},"source":["\n","train_data = rgb2gray(np.array(train_data))\n"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"zROgRekfPrAn","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":173},"outputId":"4f08fccc-2ac7-4f0a-8230-32ef032052f4","executionInfo":{"status":"ok","timestamp":1569898742297,"user_tz":-330,"elapsed":2872,"user":{"displayName":"Krunal Jain","photoUrl":"https://lh3.googleusercontent.com/a-/AAuE7mDTtvpOv4j7Rpc1DPsLIuoWRb73ePRFO18BzE2r9g=s64","userId":"06433844332726813114"}}},"source":["x = tf.placeholder(dtype = tf.float32, shape = [None, 28, 28])\n","y = tf.placeholder(dtype = tf.int32, shape = [None])\n","images_flat = tf.contrib.layers.flatten(x)\n","logits = tf.contrib.layers.fully_connected(images_flat, 100, tf.nn.relu)\n","loss = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(labels = y, logits = logits))\n","train_op = tf.train.AdamOptimizer(learning_rate=0.001).minimize(loss)\n","correct_pred = tf.argmax(logits, 1)\n","accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))\n","\n","print(\"images_flat: \", images_flat)\n","print(\"logits: \", logits)\n","print(\"loss: \", loss)\n","print(\"predicted_labels: \", correct_pred)"],"execution_count":6,"outputs":[{"output_type":"stream","text":["WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7ff9cdc902b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7ff9cdc902b0>>: AttributeError: module 'gast' has no attribute 'Num'\n","WARNING: Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7ff9cdc902b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7ff9cdc902b0>>: AttributeError: module 'gast' has no attribute 'Num'\n","WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7ff9cdc8bfd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7ff9cdc8bfd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n","WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7ff9cdc8bfd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7ff9cdc8bfd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n","images_flat:  Tensor(\"Flatten_1/flatten/Reshape:0\", shape=(?, 784), dtype=float32)\n","logits:  Tensor(\"fully_connected_1/Relu:0\", shape=(?, 100), dtype=float32)\n","loss:  Tensor(\"Mean_2:0\", shape=(), dtype=float32)\n","predicted_labels:  Tensor(\"ArgMax_1:0\", shape=(?,), dtype=int64)\n"],"name":"stdout"}]}]}